"""Fetch missing Stage 1 bundle evidence without pruning or overwriting.

The source of truth is the read-only inventory generated by
tools/audit_stage1_archive.py. Only bundles with an existing remote tar are
fetched. Existing files are retained when their SHA256 matches; mismatches are
reported and never overwritten.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
from collections import defaultdict
from pathlib import Path
from typing import Any


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def remote_copy(host: str, source: str, destination: Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    partial = destination.with_name(destination.name + ".partial")
    subprocess.run(["scp", f"{host}:{source}", str(partial)], check=True)
    partial.replace(destination)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--local-root", type=Path, default=Path("training/runs/stage1/archive"))
    parser.add_argument("--remote-inventory", type=Path, default=None)
    parser.add_argument("--catalog", type=Path, default=None)
    parser.add_argument("--remote", default="connect4_gpu_2608")
    parser.add_argument("--execute", action="store_true", help="Perform local downloads; without this flag print the plan only.")
    args = parser.parse_args()

    local_root = args.local_root.resolve()
    inventory_path = (args.remote_inventory or local_root / "catalog" / "remote_inventory.json").resolve()
    catalog_path = (args.catalog or local_root / "catalog" / "bundle_catalog.jsonl").resolve()
    inventory = load_json(inventory_path)
    catalog_rows = [json.loads(line) for line in catalog_path.read_text(encoding="utf-8").splitlines() if line.strip()]
    catalog_by_id = {row["bundle_id"]: row for row in catalog_rows if row.get("record_type") == "bundle"}

    remote_rows: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for row in inventory.get("records", []):
        if row.get("bundle_id"):
            remote_rows[str(row["bundle_id"])].append(row)

    plan = []
    for bundle_id, rows in sorted(remote_rows.items()):
        catalog_row = catalog_by_id.get(bundle_id, {})
        if catalog_row.get("content_status") == "present_verified":
            continue
        source = next((row for row in rows if row.get("archive_exists") and row.get("archive_path")), None)
        if source is None:
            plan.append({
                "bundle_id": bundle_id,
                "run_id": catalog_row.get("run_id") or next((row.get("run_id") for row in rows), None),
                "action": "blocked_remote_tar_missing",
                "manifest_paths": [row.get("manifest_path") for row in rows if row.get("manifest_path")],
            })
            continue
        run_id = str(source.get("run_id") or bundle_id.split("-", 1)[0])
        destination_dir = local_root / "bundles" / run_id
        archive_destination = destination_dir / f"{bundle_id}.tar"
        manifest_destination = destination_dir / f"{bundle_id}.manifest.json"
        plan.append({
            "bundle_id": bundle_id,
            "run_id": run_id,
            "remote_archive": source["archive_path"],
            "remote_manifest": source["manifest_path"],
            "archive_sha256": source.get("archive_sha256"),
            "archive_size_bytes": source.get("archive_size_bytes"),
            "archive_destination": str(archive_destination),
            "manifest_destination": str(manifest_destination),
            "action": "download_if_missing_or_matching",
        })

    receipt_plan = []
    local_receipt_dir = local_root / "receipts"
    local_receipt_paths = {path.name: path for path in local_receipt_dir.glob("*.receipt.json")} if local_receipt_dir.is_dir() else {}
    for receipt in inventory.get("receipts", []):
        source = receipt.get("_path")
        if not source:
            continue
        destination = local_receipt_dir / Path(source).name
        receipt_plan.append({
            "remote": source,
            "destination": str(destination),
            "action": "download_if_missing_or_matching" if destination.name not in local_receipt_paths else "already_present_check_sha256",
        })

    if not args.execute:
        print(json.dumps({"execute": False, "bundle_plan": plan, "receipt_plan": receipt_plan}, ensure_ascii=False, indent=2))
        return 0

    fetched = []
    skipped = []
    conflicts = []
    for item in plan:
        if item["action"] == "blocked_remote_tar_missing":
            skipped.append(item)
            continue
        archive_destination = Path(item["archive_destination"])
        manifest_destination = Path(item["manifest_destination"])
        source = next(row for row in remote_rows[item["bundle_id"]] if row.get("archive_path") == item["remote_archive"])
        if archive_destination.is_file():
            if sha256_file(archive_destination) != item["archive_sha256"]:
                conflicts.append({"path": str(archive_destination), "reason": "existing_archive_sha256_differs", "bundle_id": item["bundle_id"]})
                continue
        else:
            remote_copy(args.remote, item["remote_archive"], archive_destination)
            if sha256_file(archive_destination) != item["archive_sha256"]:
                conflicts.append({"path": str(archive_destination), "reason": "downloaded_archive_sha256_differs", "bundle_id": item["bundle_id"]})
                continue
            fetched.append(str(archive_destination))
        if manifest_destination.is_file():
            if sha256_file(manifest_destination) != source.get("manifest_sha256"):
                conflicts.append({"path": str(manifest_destination), "reason": "existing_manifest_sha256_differs", "bundle_id": item["bundle_id"]})
        else:
            remote_copy(args.remote, source["manifest_path"], manifest_destination)
            if sha256_file(manifest_destination) != source.get("manifest_sha256"):
                conflicts.append({"path": str(manifest_destination), "reason": "downloaded_manifest_sha256_differs", "bundle_id": item["bundle_id"]})
            else:
                fetched.append(str(manifest_destination))

    for item in receipt_plan:
        destination = Path(item["destination"])
        if destination.is_file():
            remote_receipt = next(r for r in inventory["receipts"] if r.get("_path") == item["remote"])
            # A receipt's serialized remote object includes the inventory-only _path
            # field, so compare its actual source after a fetch instead of using it
            # as an integrity hash.
            if load_json(destination).get("receipt_id") == remote_receipt.get("receipt_id"):
                skipped.append({"path": str(destination), "reason": "receipt_id_already_present"})
            else:
                conflicts.append({"path": str(destination), "reason": "receipt_identity_differs"})
            continue
        remote_copy(args.remote, item["remote"], destination)
        fetched.append(str(destination))

    print(json.dumps({
        "execute": True,
        "fetched_count": len(fetched),
        "fetched": fetched,
        "skipped_count": len(skipped),
        "blocked_or_skipped": skipped,
        "conflict_count": len(conflicts),
        "conflicts": conflicts,
        "note": "No remote file was deleted or modified.",
    }, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
